#!/bin/bash

TRAVIS_BUILD_DIR=$(dirname $(readlink -f $0))

set -ex

cd $TRAVIS_BUILD_DIR/example-f401-board && cargo build --release --bins --examples
cd $TRAVIS_BUILD_DIR/example-f407-board && cargo build --release --bins --examples
cd $TRAVIS_BUILD_DIR/example-f429zi-board && cargo build --release --bins --examples --features fs
cd $TRAVIS_BUILD_DIR/example-f429zi-board && cargo build --release --bins --examples --features hs
cd $TRAVIS_BUILD_DIR/example-f446re-board && cargo build --release --bins --examples --features fs
cd $TRAVIS_BUILD_DIR/example-f446re-board && cargo build --release --bins --examples --features hs
cd $TRAVIS_BUILD_DIR/example-f446ze-board && cargo build --release --bins --examples --features fs
cd $TRAVIS_BUILD_DIR/example-f446ze-board && cargo build --release --bins --examples --features hs
cd $TRAVIS_BUILD_DIR/example-f723e-disco-board && cargo build --release --examples --features fs
cd $TRAVIS_BUILD_DIR/example-f723e-disco-board && cargo build --release --examples --features hs
cd $TRAVIS_BUILD_DIR/example-longan-nano-board && cargo build --release --bins --examples
cd $TRAVIS_BUILD_DIR/example-stlinkv3-board && cargo build --release --examples --features fs
cd $TRAVIS_BUILD_DIR/example-stlinkv3-board && cargo build --release --examples --features hs
cd $TRAVIS_BUILD_DIR/example-xcore407i-board && cargo build --release --bins --examples --features fs
cd $TRAVIS_BUILD_DIR/example-xcore407i-board && cargo build --release --bins --examples --features hs
