[workspace]

members = [
    "example-f401-board",
    "example-f429zi-board",
    "stm32-log",
    "stm32f4xx-hal",
    "stm32f429-usbd-fs",
    "stm32ral",
    "synopsys-usb-otg",
]

[patch.crates-io]
stm32-log = { path = "stm32-log" }
stm32f4xx-hal = { path = "stm32f4xx-hal" }
stm32f429-usbd-fs = { path = "stm32f429-usbd-fs" }
synopsys-usb-otg = { path = "synopsys-usb-otg" }
stm32ral = { path = "stm32ral" }
