[workspace]

members = [
    "stm32f4xx-hal",
    "stm32f429-usbd-fs",
    "usb-device",
]

[patch.crates-io]
stm32f4xx-hal = { path = "stm32f4xx-hal" }
stm32f429-usbd-fs = { path = "stm32f429-usbd-fs" }
usb-device = { path = "usb-device" }
